cache:
  directories:
  - node_modules
branches:
  only:
  - master
language: node_js
node_js:
- 6.9.1
before_install:
- rvm install 2.3.1
- bundle install
install:
- npm install -g gulp
- npm install
script:
- gulp build
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages -e; fi