cache:
  directories:
  - node_modules
branches:
  only:
  - master
language: node_js
node_js:
- 6.9.1
before_install:
- rvm install 2.3.1
- bundle install
install:
- npm install -g gulp
- npm install
- bower install
script:
- gulp build
after_success: bash ./bin/deploy.sh