# Site settings
title: Business Casual
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
repository: 'egeis/jekyll-business-casual'
url: ''
#url: 'https://egeis.github.io/jekyll-business-casua'

#Theme Settings
address: "3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890"
copyright: "Your website"
links:
 - url: "https://github.com/egeis/jekyll-business-casual"
   display-order: 1
   icon: "fa-github-square"
 - url: "https://www.linkedin.com/"
   display-order: 0
   icon: "fa-linkedin-square"
 - url: "https://www.facebook.com/"
   display-order: 2
   icon: "fa-facebook-square"
   
# Markdown Settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
highlighter: rouge

# Outputting
source: src
permalink: /:title/
destination: public

# Build Settings
gems:
  - jekyll-feed
  - jekyll-sitemap  
  - octopress-paginate
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - octopress-paginate
include:
  - .htaccess
  - _pages
  - README.md
  - LICENSE.md
exclude:
  - Gemfile
  - Gemfile.lock
  - CHANGELOG.md
  - .sass-cache
  - .asset-cache
  - .bundle
  - vendor
  - log
  - node_modules
  - bower_components
  - gulpfile.js
  - package.json
  - assets
  - .nojekyll
  - .git
  - .travis
  - bower.json
keep_files:
 - assets
 
encoding: "utf-8"

# Collection Settings
collections:
   posts:
     permalink: /blog/:year/:month/:day/:title.html
     output: true
   members:
     output: false

paginate:
  per_page: 3 
  limit: 5   
  title_suffix: " - page :num"
  reversed: false 
  
prose: 
  ignore: 
    - /src/_layouts
    - /src/_includes
    - /src/_plugins
    - /src/*.html
    - /src/_sass
  media: /assets/images/uploads
  metadata: 
    src/_posts: 
      -
       name: "frontimagesrc"
       field:
         element: "text"
         label: "Front Image - Source"
      -
       name: "frontimagealt"
       field:
         element: "text"
         label: "Front Image - Description"
      -
       name: "date"
       field:
         element: "text"
         label: "Date"
         value: "CURRENT_DATETIME"
      - 
        field: 
          element: hidden
          value: blog
        name: "layout"
      - 
        field: 
          element: text
          label: title
        name: "title"